import { writeFile, mkdir } from 'fs/promises'
import { join, dirname } from 'path'
import type { ToolDefinition } from '../types'

export const definition: ToolDefinition = {
  name: 'write_briefing',
  description:
    'Generate and save a structured interview preparation briefing for a company. Includes company overview, culture, recent developments, key talking points, and suggested questions to ask.',
  parameters: {
    type: 'object',
    properties: {
      filename: {
        type: 'string',
        description: 'Filename for the briefing (e.g. "acme-corp-briefing.md")',
      },
      company_name: {
        type: 'string',
        description: 'Name of the company',
      },
      role_title: {
        type: 'string',
        description: 'The role you\'re interviewing for',
      },
      company_overview: {
        type: 'string',
        description: 'What the company does, products/services, market position',
      },
      culture_and_values: {
        type: 'string',
        description: 'Company culture, values, work environment, Glassdoor insights',
      },
      recent_developments: {
        type: 'string',
        description: 'Recent news, product launches, funding rounds, leadership changes',
      },
      key_people: {
        type: 'string',
        description: 'CEO, founders, hiring manager if known, notable leaders',
      },
      talking_points: {
        type: 'string',
        description: 'Newline-separated talking points to mention during the interview',
      },
      questions_to_ask: {
        type: 'string',
        description: 'Newline-separated smart questions to ask the interviewer',
      },
      red_flags: {
        type: 'string',
        description: 'Any concerns or red flags to be aware of (optional)',
      },
    },
    required: ['filename', 'company_name', 'company_overview', 'talking_points', 'questions_to_ask'],
  },
}

export async function execute(args: Record<string, unknown>): Promise<string> {
  const filename = args.filename as string
  const companyName = args.company_name as string
  const roleTitle = (args.role_title as string) || 'the role'
  const overview = args.company_overview as string
  const culture = (args.culture_and_values as string) || 'No specific culture data found — research this independently.'
  const recentDev = (args.recent_developments as string) || 'No recent developments found.'
  const keyPeople = (args.key_people as string) || 'Research the team page before your interview.'
  const talkingPoints = args.talking_points as string
  const questions = args.questions_to_ask as string
  const redFlags = (args.red_flags as string) || ''

  if (!filename || !companyName || !overview || !talkingPoints || !questions) {
    return 'Error: filename, company_name, company_overview, talking_points, and questions_to_ask are required'
  }

  const briefing = `# Interview Briefing: ${companyName}
## Role: ${roleTitle}

**Prepared**: ${new Date().toISOString().split('T')[0]}
**Read time**: ~3 minutes

---

## What They Do

${overview}

## Culture & Values

${culture}

## Recent Developments

${recentDev}

## Key People

${keyPeople}

---

## Your Talking Points

Use these to show you've done your homework:

${talkingPoints.split('\n').filter(Boolean).map(p => `- ${p.trim()}`).join('\n')}

## Smart Questions to Ask

These show genuine interest and research:

${questions.split('\n').filter(Boolean).map(q => `- "${q.trim()}"`).join('\n')}

${redFlags ? `## Watch Out For

${redFlags.split('\n').filter(Boolean).map(f => `- ⚠️ ${f.trim()}`).join('\n')}
` : ''}
---

## Quick Prep Checklist

- [ ] Read through this briefing
- [ ] Visit the company's website and recent blog posts
- [ ] Check LinkedIn for your interviewer's background
- [ ] Prepare 2-3 stories that connect your experience to their mission
- [ ] Review the job description one more time
- [ ] Prepare your "tell me about yourself" answer tailored to this company

---

*Generated by Company Briefing Agent — an open-source AI agent for interview preparation*
`

  const sanitized = filename.replace(/[^a-zA-Z0-9._-]/g, '_')
  const outputDir = join(process.cwd(), 'output')
  const filePath = join(outputDir, sanitized)

  try {
    await mkdir(dirname(filePath), { recursive: true })
    await writeFile(filePath, briefing, 'utf-8')
    return `Briefing saved to output/${sanitized} (${briefing.length} characters)\n\nYour interview briefing for ${companyName} is ready. Good luck!`
  } catch (err) {
    return `Briefing write error: ${err instanceof Error ? err.message : 'Unknown error'}`
  }
}
