import { writeFile, mkdir } from 'fs/promises'
import { join, dirname } from 'path'
import type { ToolDefinition } from '../types'

export const definition: ToolDefinition = {
  name: 'write_trust_report',
  description:
    'Generate and save a trust report for an npm package. Includes a trust score, risk factors, positive signals, and an install recommendation (SAFE / CAUTION / AVOID).',
  parameters: {
    type: 'object',
    properties: {
      filename: {
        type: 'string',
        description: 'Filename for the report (e.g. "express-trust-report.md")',
      },
      package_name: {
        type: 'string',
        description: 'The npm package name',
      },
      trust_score: {
        type: 'string',
        description: 'Trust score from 1 (do not install) to 10 (highly trusted)',
      },
      recommendation: {
        type: 'string',
        description: 'Install recommendation: SAFE / CAUTION / AVOID',
      },
      risk_factors: {
        type: 'string',
        description: 'Newline-separated list of risk factors found',
      },
      positive_signals: {
        type: 'string',
        description: 'Newline-separated list of positive trust signals',
      },
      security_summary: {
        type: 'string',
        description: 'Summary of security findings (CVEs, malware reports, repo health)',
      },
      details: {
        type: 'string',
        description: 'Detailed analysis explaining the trust assessment',
      },
      alternatives: {
        type: 'string',
        description: 'Suggested alternative packages if the package is risky (optional)',
      },
    },
    required: ['filename', 'package_name', 'trust_score', 'recommendation', 'risk_factors', 'positive_signals', 'details'],
  },
}

export async function execute(args: Record<string, unknown>): Promise<string> {
  const filename = args.filename as string
  const packageName = args.package_name as string
  const trustScore = args.trust_score as string
  const recommendation = args.recommendation as string
  const riskFactors = args.risk_factors as string
  const positiveSignals = args.positive_signals as string
  const securitySummary = (args.security_summary as string) || 'See details below.'
  const details = args.details as string
  const alternatives = (args.alternatives as string) || ''

  if (!filename || !packageName || !trustScore || !recommendation || !details) {
    return 'Error: filename, package_name, trust_score, recommendation, and details are required'
  }

  const score = parseInt(trustScore, 10)
  const emoji = score >= 7 ? '🟢' : score >= 4 ? '🟡' : '🔴'
  const label = score >= 7 ? 'TRUSTED' : score >= 4 ? 'USE CAUTION' : 'HIGH RISK'

  const report = `# npm Trust Report: ${packageName}

## ${emoji} Trust Score: ${trustScore}/10 — ${label}

| Field | Value |
|-------|-------|
| **Package** | ${packageName} |
| **Recommendation** | **${recommendation}** |
| **Generated** | ${new Date().toISOString().split('T')[0]} |

---

## Risk Factors

${riskFactors.split('\n').filter(Boolean).map(f => `- ⚠️ ${f.trim()}`).join('\n') || '- None identified'}

## Positive Signals

${positiveSignals.split('\n').filter(Boolean).map(s => `- ✅ ${s.trim()}`).join('\n') || '- None identified'}

## Security Summary

${securitySummary}

## Detailed Analysis

${details}

${alternatives ? `## Alternative Packages

If this package is too risky, consider these alternatives:

${alternatives.split('\n').filter(Boolean).map(a => `- ${a.trim()}`).join('\n')}
` : ''}
---

## Pre-Install Checklist

${score >= 7 ? `This package appears trustworthy. Standard precautions:
- [ ] Verify the package name is spelled correctly (typosquatting is common)
- [ ] Lock your version in package.json (avoid \`latest\`)
- [ ] Run \`npm audit\` after installing` :
score >= 4 ? `Proceed with caution:
- [ ] Verify the package name is spelled correctly
- [ ] Check the GitHub repository manually
- [ ] Review the package's source code, especially install scripts
- [ ] Consider whether you really need this dependency
- [ ] Run \`npm audit\` and \`npx npm-check\` after installing
- [ ] Set up Snyk or Socket.dev for ongoing monitoring` :
`This package has significant trust issues:
- [ ] Do NOT install without thorough manual review
- [ ] Check if a more established alternative exists
- [ ] If you must use it, audit the source code line by line
- [ ] Disable install scripts: \`npm install --ignore-scripts\`
- [ ] Consider vendoring the code instead of depending on it`}

---

*Generated by npm Trust Checker — an open-source AI agent for supply chain security*
`

  const sanitized = filename.replace(/[^a-zA-Z0-9._-]/g, '_')
  const outputDir = join(process.cwd(), 'output')
  const filePath = join(outputDir, sanitized)

  try {
    await mkdir(dirname(filePath), { recursive: true })
    await writeFile(filePath, report, 'utf-8')
    return `Trust report saved to output/${sanitized} (${report.length} characters)\n\nSummary: ${emoji} ${label} (${trustScore}/10) — ${recommendation}`
  } catch (err) {
    return `Report write error: ${err instanceof Error ? err.message : 'Unknown error'}`
  }
}
